---
title: "Non-Coding RNAs Improve the Predictive Power of Network Medicine"
author: "Deisy Morselli Gysi and Albert-László Barabási"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-title: Contents
    embed-resources: true
editor: visual
theme: Flatly
---

Codes accompanying the paper "Non-Coding RNAs Improve the Predictive Power of Network Medicine" by D.M. Gysi & A.L. Barabasi doi: \<\>.

-   Codes for the manuscript can be found in the folder: `./code`
    -   Code that reproduces results in manuscript and SI can be found in `00_Load.qmd`
    -   Code that run LCC, S\_{ab}, Jaccard Index are in `01_LCC_Sab.R`
    -   To recalculate co-expression network based on PCC and wTO, please refer to `02_Corr.R`.
    -   To calculate performance of the co-expression networks, please refer to `03_Corr_Performance.R`.
-   Raw data necessary for reproducing the codes: `./data/input`.
-   Raw datasets used to compute the co-expression networks are found in [GTEx dataset webpage](https://www.gtexportal.org/home/datasets "GTEx dataset webpage").
-   Outcomes can be found in `./data/output`
-   Figures generated by the codes can be found in `./figs`
